Repository profanity-im/profanity, pull requests merged in 2019-04, with the labels that each got.

#1039 Feature/omemo
  Makefile.am
  configure.ac
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/command/cmd_funcs.h
  src/config/files.h
  src/config/preferences.c
  src/config/preferences.h
  src/event/client_events.c
  src/event/server_events.c
  src/event/server_events.h
  src/log.c
  src/log.h
  src/main.c
  src/omemo/crypto.c
  src/omemo/crypto.h
  src/omemo/omemo.c
  src/omemo/omemo.h
  src/omemo/store.c
  src/omemo/store.h
  src/plugins/api.c
  src/profanity.c
  src/ui/chatwin.c
  src/ui/console.c
  src/ui/mucwin.c
  src/ui/titlebar.c
  src/ui/ui.h
  src/ui/win_types.h
  src/ui/window.c
  src/ui/window_list.c
  src/xmpp/connection.c
  src/xmpp/connection.h
  src/xmpp/iq.c
  src/xmpp/iq.h
  src/xmpp/message.c
  src/xmpp/message.h
  src/xmpp/omemo.c
  src/xmpp/omemo.h
  src/xmpp/roster.c
  src/xmpp/session.c
  src/xmpp/stanza.c
  src/xmpp/stanza.h
  src/xmpp/xmpp.h
  tests/unittests/log/stub_log.c
  tests/unittests/omemo/stub_omemo.c
  tests/unittests/ui/stub_ui.c
  tests/unittests/xmpp/stub_xmpp.c
Labels: feature

#1054 Don't touch OMEMO cryto keys on disconnect if OMEMO wasn't loaded
  src/omemo/omemo.c
Labels: OMEMO

#1061 Handle message without id in MUC
  src/ui/mucwin.c
Labels: bug

#1064 Alert about long OMEMO cryptographic generation
  src/command/cmd_funcs.c
Labels: improvement

#1062 Add OMEMO policy
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/command/cmd_funcs.h
  src/config/account.c
  src/config/account.h
  src/config/accounts.c
  src/config/accounts.h
  src/config/preferences.c
  src/config/preferences.h
  src/omemo/omemo.c
  src/omemo/omemo.h
  src/ui/chatwin.c
  src/ui/console.c
  src/ui/core.c
  src/ui/mucwin.c
  src/ui/ui.h
  src/xmpp/iq.c
  tests/unittests/config/stub_accounts.c
  tests/unittests/omemo/stub_omemo.c
  tests/unittests/test_cmd_account.c
  tests/unittests/test_cmd_connect.c
  tests/unittests/test_cmd_join.c
  tests/unittests/test_cmd_otr.c
  tests/unittests/test_cmd_rooms.c
Labels: improvement

#1063 Handle presence received before roster
  src/event/server_events.c
  src/xmpp/roster_list.c
  src/xmpp/roster_list.h
  tests/unittests/test_server_events.c
Labels: bug

#1071 Add library versioning to libprofanity
  Makefile.am
Labels: improvement

#1073 Fix indentation time confing
  src/ui/console.c
Labels: improvement

#1078 Fix statusbar number in theme
  src/config/theme.c
Labels: bug

#1080 OMEMO: Check if ID is present before using it
  src/xmpp/omemo.c
Labels: bug
