Repository profanity-im/profanity, pull requests merged in 2019-08, with the labels that each got.

#1166 Don't print subscribed message if contact is already in roster
  src/event/server_events.c
Labels: improvement

#1167 Possibility to specify alternative config file
  docs/profanity.1
  src/config/preferences.c
  src/config/preferences.h
  src/main.c
  src/profanity.c
  src/profanity.h
  tests/unittests/helpers.c
Labels: feature

#1175 Added solarized theme
  themes/solarized-dark
Labels: theme

#1174 Don't render (all) delayed messages as MUC history
  src/xmpp/message.c
  src/xmpp/stanza.c
  src/xmpp/stanza.h
Labels: improvement

#1177 Add 256 colors support
  Makefile.am
  src/config/color.c
  src/config/color.h
  src/config/theme.c
Labels: feature
