Repository profanity-im/profanity, pull requests merged in 2019-07, with the labels that each got.

#1146 Fix several OMEMO related leaks
  src/omemo/omemo.c
  src/omemo/omemo.h
  src/profanity.c
  src/xmpp/iq.c
  src/xmpp/omemo.c
Labels: OMEMO

#1157 Fix segfault in block command
  src/xmpp/blocking.c
Labels: bug

#1154 Always check for directory changes with sendfile auto completion
  src/command/cmd_ac.c
  src/tools/autocomplete.c
  src/tools/autocomplete.h
Labels: improvement

#1160 Fix segfault in group add/remove command
  src/xmpp/roster.c
Labels: bug
