Repository profanity-im/profanity, pull requests merged in 2019-05, with the labels that each got.

#1084 Add occupants char
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/config/preferences.c
  src/config/preferences.h
  src/config/theme.c
  src/ui/console.c
  src/ui/occupantswin.c
  theme_template
Labels: improvement

#1090 Reset things on connection loss
  src/event/server_events.c
Labels: bug

#1097 Create seperate function for disconnect cleanup
  Makefile.am
  src/event/client_events.c
  src/event/common.c
  src/event/common.h
  src/event/server_events.c
Labels: improvement

#1098 Force UI update before generating OMEMO crypto materials
  src/command/cmd_funcs.c
Labels: improvement

#1102 Correctly handle malformed OMEMO messages
  src/omemo/omemo.c
Labels: OMEMO, bug

#1092 Don't call mblen() to not depend on locale
  src/common.c
Labels: improvement
