Repository profanity-im/profanity, pull requests merged in 2019-06, with the labels that each got.

#1104 xmpp/connection: fix #1103
  src/xmpp/connection.c
Labels: bug

#1105 Cancel autoping timer on disconnect or connection loss
  src/event/common.c
  src/xmpp/iq.c
  src/xmpp/xmpp.h
  tests/unittests/xmpp/stub_xmpp.c
Labels: improvement

#1106 Don't clear saved account data in session_disconnect()
  src/xmpp/session.c
Labels: improvement

#1109 Fix SIGABRT on lost connection
  src/ui/statusbar.c
  src/xmpp/roster_list.c
  src/xmpp/roster_list.h
Labels: bug

#1111 Add omemo.char to themes
  src/config/theme.c
  theme_template
  themes/bios
  themes/boothj5
  themes/boothj5_laptop
  themes/boothj5_slack
Labels: improvement

#1113 Check autoconnect set settings
  src/command/cmd_funcs.c
Labels: improvement

#1108 Use travis matrix to test more systems (#1100)
  .travis.yml
  Brewfile.travis
  Dockerfile.arch
  Dockerfile.debian
  Dockerfile.tumbleweed
  bootstrap.sh
  travis-build.sh
Labels: improvement, tests

#1121 Improve plugin load/install failure message
  src/command/cmd_funcs.c
  src/plugins/plugins.c
  src/plugins/plugins.h
Labels: improvement

#1118 Only complete certain omemo commands if connected
  src/command/cmd_ac.c
Labels: OMEMO, bug

#1123 Print omemo start related msgs into correct window
  src/command/cmd_funcs.c
Labels: improvement

#1124 Remove OMEMO session when untrusting a fingerprint
  src/omemo/omemo.c
  src/omemo/store.c
Labels: OMEMO, improvement

#1125 Iterate logfiles until 100 are reached
  src/log.c
Labels: improvement

#1127 Rejoin all MUCs on reconnect
  src/event/server_events.c
Labels: bug

#1110 Feature/704 ui behaviour reconnect
  src/event/server_events.c
  src/ui/mucwin.c
  src/ui/win_types.h
  src/ui/window_list.c
  src/ui/window_list.h
Labels: improvement

#1129 Add option to set all window related time formats
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
Labels: feature

#1130 Fix memory leaks
  src/omemo/omemo.c
  src/ui/statusbar.c
  src/xmpp/bookmark.c
  src/xmpp/iq.c
  src/xmpp/message.c
  src/xmpp/message.h
  src/xmpp/session.c
  src/xmpp/xmpp.h
  tests/unittests/test_cmd_otr.c
  tests/unittests/test_cmd_presence.c
  tests/unittests/test_preferences.c
Labels: bug

#1126 Decrypt all incoming omemo msg
  Makefile.am
  src/config/theme.c
  src/config/theme.h
  src/event/client_events.c
  src/event/server_events.c
  src/event/server_events.h
  src/log.c
  src/log.h
  src/omemo/omemo.c
  src/omemo/omemo.h
  src/omemo/store.c
  src/omemo/store.h
  src/otr/otr.c
  src/plugins/api.c
  src/ui/chatwin.c
  src/ui/mucwin.c
  src/ui/privwin.c
  src/ui/ui.h
  src/ui/window.c
  src/ui/window.h
  src/xmpp/message.c
  src/xmpp/message.h
  src/xmpp/omemo.c
  src/xmpp/omemo.h
  tests/unittests/log/stub_log.c
  tests/unittests/ui/stub_ui.c
  theme_template
  themes/boothj5
Labels: improvement

#1132 Fix NULL pointer when handling non encrypted message in MUC
  src/xmpp/message.c
Labels: OMEMO, bug

#1135 Fix handling of encrypted carbons
  src/event/server_events.c
  src/ui/chatwin.c
  src/ui/ui.h
  tests/unittests/ui/stub_ui.c
Labels: bug

#1136 Fix a segfault when carbon has no body
  src/xmpp/message.c
Labels: bug

#1137 Mark messages received from a session as trusted
  src/omemo/omemo.c
  src/omemo/store.c
  src/omemo/store.h
Labels: OMEMO
