Repository profanity-im/profanity, pull requests merged in 2020-06, with the labels that each got.

#1352 Initialize ProfWin.urls_ac to NULL to fix OpenBSD build
  tests/unittests/test_cmd_otr.c
Labels: improvement

#1349 configure.ac: add additional check for libstrophe
  configure.ac
Labels: improvement

#1355 Add option for legacy authentication
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/config/account.c
  src/config/account.h
  src/config/accounts.c
  src/config/accounts.h
  src/event/client_events.c
  src/event/client_events.h
  src/ui/console.c
  src/xmpp/connection.c
  src/xmpp/connection.h
  src/xmpp/session.c
  src/xmpp/xmpp.h
  tests/unittests/config/stub_accounts.c
  tests/unittests/test_cmd_account.c
  tests/unittests/test_cmd_connect.c
  tests/unittests/test_cmd_join.c
  tests/unittests/test_cmd_otr.c
  tests/unittests/test_cmd_rooms.c
  tests/unittests/xmpp/stub_xmpp.c
Labels: feature

#1356 Bump OpenBSD build to 6.7
  .builds/openbsd.yml
Labels: tests

#1360 Make legacy auth optional
  configure.ac
  src/xmpp/connection.c
Labels: improvement

#1363 Clean-up task: clean up feature defines
  src/command/cmd_funcs.c
  src/event/client_events.c
  src/event/server_events.c
Labels: cleanup
