Repository profanity-im/profanity, pull requests merged in 2020-12, with the labels that each got.

#1445 Create cmd to generate man pages for prof commands
  Makefile.am
  RELEASE_GUIDE.md
  docs/profanity.1
  src/command/cmd_defs.c
  src/command/cmd_defs.h
  src/main.c
Labels: improvement

#1447 omemo media sharing related polishing
  src/command/cmd_funcs.c
  src/common.c
  src/common.h
  src/config/preferences.c
Labels: cleanup, improvement

#1446 Fix chatlogs for outgoing carbons
  src/event/server_events.c
Labels: bug

#1451 docs: fix simple typo, certian -> certain
  src/config/theme.c
Labels: cleanup

#1450 Cast chat/muc window to correct type and refactor cmd_sendfile
  src/command/cmd_funcs.c
  src/common.c
  src/ui/chatwin.c
Labels: OMEMO, bug

#1454 Create download directory under XDG data path
  src/command/cmd_funcs.c
  src/tools/http_download.c
Labels: OMEMO, bug, improvement

#1455 Use whole path as logfile when defined via -f
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/config/files.c
  src/log.c
  src/log.h
  tests/unittests/log/stub_log.c
Labels: behaviour-change, improvement

#1456 Fix color for win_print_outgoing()
  src/ui/window.c
Labels: UI, bug

#1460 Remove blank line after trackbar
  src/ui/window.c
Labels: UI, improvement

#1461 Set input window size to max window size
  src/ui/inputwin.c
Labels: UI, improvement

#1459 Restore old behavior when executing eval_password command
  src/common.c
  src/common.h
  src/config/account.c
Labels: bug

#1462 Switch from Travis CI to GitHub Actions
  .github/workflows/main.yml
  .travis.yml
  Brewfile
Labels: improvement, tests

#1463 Add `/executable (urlsave|urlopen)` migrations
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/config/preferences.c
Labels: cleanup

#1465 Print logs on error in CI
  ci-build.sh
Labels: bug, improvement, tests
