Repository profanity-im/profanity, pull requests merged in 2020-05, with the labels that each got.

#1341 Add urlopen command
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/command/cmd_funcs.h
  src/common.c
  src/common.h
  src/config/preferences.c
  src/config/preferences.h
  src/tools/autocomplete.c
  src/tools/autocomplete.h
  src/ui/chatwin.c
  src/ui/console.c
  src/ui/mucwin.c
  src/ui/privwin.c
  src/ui/ui.h
  src/ui/win_types.h
  src/ui/window_list.c
  src/ui/window_list.h
  src/xmpp/avatar.c
Labels: feature

#1344 Bugfix: Status with PGP shows offline in titlebar
  src/event/server_events.c
Labels: bug

#1343 Incoming iq stanza - Reset the autoping timer
  src/xmpp/iq.c
Labels: improvement
