Repository profanity-im/profanity, pull requests merged in 2020-02, with the labels that each got.

#1267 XEP-0308 Last Message Correction
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/command/cmd_funcs.h
  src/config/preferences.c
  src/config/preferences.h
  src/config/theme.c
  src/event/client_events.c
  src/event/client_events.h
  src/omemo/omemo.c
  src/omemo/omemo.h
  src/otr/otr.c
  src/otr/otr.h
  src/tools/parser.c
  src/ui/buffer.c
  src/ui/buffer.h
  src/ui/chatwin.c
  src/ui/console.c
  src/ui/mucwin.c
  src/ui/privwin.c
  src/ui/ui.h
  src/ui/win_types.h
  src/ui/window.c
  src/ui/window.h
  src/xmpp/capabilities.c
  src/xmpp/message.c
  src/xmpp/stanza.c
  src/xmpp/stanza.h
  src/xmpp/xmpp.h
  tests/unittests/otr/stub_otr.c
  tests/unittests/ui/stub_ui.c
  tests/unittests/xmpp/stub_xmpp.c
  theme_template
  themes/boothj5
Labels: feature

#1269 Add builds.sr.ht CI for OpenBSD
  .builds/openbsd.yml
  .travis.yml
  ci-build.sh
  configure.ac
  src/ui/rosterwin.c
  tests/unittests/test_cmd_otr.c
Labels: improvement, tests

#1273 Add builds.sr.ht badge for Profanity builds
  README.md
Labels: improvement, tests

#1278 Fix few memory leaks
  src/config/preferences.c
  src/main.c
  src/xmpp/iq.c
Labels: improvement
