Repository profanity-im/profanity, pull requests merged in 2020-07, with the labels that each got.

#1374 Rework /url and /executable for filetypes
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/command/cmd_funcs.h
  src/config/preferences.c
  src/config/preferences.h
  src/ui/console.c
  src/ui/window_list.c
Labels: discussion, feature

#1386 Rework logging
  src/log.c
  src/main.c
Labels: behaviour-change, cleanup

#1394 Log errors from eval_password
  src/config/account.c
Labels: improvement

#1397 Tip about pre-push hook in contribution guidelines
  CONTRIBUTING.md
Labels: cleanup

#1400 Dont hilight console once all messages have been read
  src/command/cmd_funcs.c
  src/event/server_events.c
  src/plugins/api.c
  src/ui/chatwin.c
  src/ui/console.c
  src/ui/core.c
  src/ui/privwin.c
  src/ui/ui.h
  src/ui/window_list.c
  tests/unittests/ui/stub_ui.c
Labels: improvement

#1402 Ubuntu Latest (20.04 currently) in CI
  .travis.yml
  Dockerfile.ubuntu
Labels: tests

#1403 Free errors after they have been printed
  src/omemo/omemo.c
Labels: cleanup

#1407 Change to .tar.zst archives that latest Arch devtools uses
  Dockerfile.arch
Labels: tests

#1408 parser.c: Use helper function to reduce duplicate code
  src/tools/parser.c
Labels: cleanup

#1410 Fix missed text in #1224
  src/command/cmd_defs.c
Labels: improvement

#1413 MAM: Only add each message once to database
  src/database.c
  src/xmpp/message.c
  src/xmpp/stanza.h
  src/xmpp/xmpp.h
Labels: feature
