Repository profanity-im/profanity, pull requests merged in 2020-08, with the labels that each got.

#1416 Fix memory leak in _handle_chat()
  src/xmpp/message.c
Labels: cleanup

#1415 configure: support gtk3 too
  configure.ac
Labels: improvement

#1421 Update gruvbox theme (background color)
  themes/gruvbox
Labels: improvement, theme
