Repository profanity-im/profanity, pull requests merged in 2021-07, with the labels that each got.

#1529 Access roster from plugins
  apidocs/c/profapi.h
  apidocs/python/src/prof.py
  src/plugins/api.c
  src/plugins/api.h
  src/plugins/c_api.c
  src/plugins/profapi.c
  src/plugins/profapi.h
  src/plugins/python_api.c
  src/xmpp/roster_list.c
  src/xmpp/roster_list.h
  tests/unittests/test_roster_list.c
  tests/unittests/test_roster_list.h
  tests/unittests/unittests.c
Labels: feature, plugins

#1570 Restore last status string when connecting
  src/config/accounts.c
  src/config/accounts.h
  src/event/server_events.c
  tests/unittests/config/stub_accounts.c
Labels: improvement

#1569 Add XEP-0377: Spam Reporting
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/xmpp/blocking.c
  src/xmpp/iq.c
  src/xmpp/stanza.h
  src/xmpp/xmpp.h
  tests/unittests/xmpp/stub_xmpp.c
Labels: feature

#1571 Add option to only allow messages from jids in roster
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/command/cmd_funcs.h
  src/config/preferences.c
  src/config/preferences.h
  src/ui/console.c
  src/ui/ui.h
  src/xmpp/message.c
  tests/unittests/ui/stub_ui.c
Labels: feature

#1566 Bugfixes for OX implementation
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/pgp/gpg.c
  src/xmpp/message.c
  src/xmpp/ox.c
Labels: improvement, ox

#1573 Initialize jid
  src/command/cmd_funcs.c
Labels: bug

#1576 OMEMO autocomplete untrust
  src/command/cmd_ac.c
Labels: OMEMO, improvement

#1577 Fix examples in python API doc
  apidocs/python/src/prof.py
Labels: cleanup

#1586 Fix invalid reads on mentions in MUC
  src/ui/mucwin.c
Labels: cleanup, improvement
