Repository profanity-im/profanity, pull requests merged in 2021-05, with the labels that each got.

#1532 Have separate settings for intype (console/titlebar)
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/config/preferences.c
  src/config/preferences.h
  src/ui/console.c
  src/ui/core.c
Labels: behaviour-change, improvement

#1534 Use direct messages instead of MUC-PMs for non-anonymous MUCs
  src/command/cmd_funcs.c
Labels: behaviour-change, improvement

#1539 Improved OMEMO logging
  src/omemo/omemo.c
  src/omemo/store.c
  src/xmpp/message.c
  src/xmpp/omemo.c
Labels: cleanup, improvement

#1540 Display OMEMO device ID
  src/command/cmd_funcs.c
  tests/unittests/omemo/stub_omemo.c
Labels: OMEMO, improvement

#1546 external editor: don't use absolute paths and allow path search
  src/command/cmd_funcs.c
  src/config/preferences.c
Labels: improvement

#1543 Feature - attention flag
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/command/cmd_funcs.h
  src/ui/console.c
  src/ui/core.c
  src/ui/inputwin.c
  src/ui/titlebar.c
  src/ui/ui.h
  src/ui/win_types.h
  src/ui/window.c
  src/ui/window_list.c
  src/ui/window_list.h
  tests/unittests/ui/stub_ui.c
Labels: feature
