Repository profanity-im/profanity, pull requests merged in 2021-06, with the labels that each got.

#1548 OMEMO - Unable to publish own device list
  src/omemo/omemo.c
  src/xmpp/omemo.c
Labels: OMEMO

#1549 Restart OMEMO Session after lost connection
  src/ui/window_list.c
Labels: OMEMO, improvement

#1542 OMEMO: Don't encrypt to yourself (MUC)
  src/omemo/omemo.c
Labels: OMEMO

#1550 Message received without body error log
  src/xmpp/message.c
Labels: cleanup

#1557 Fix wrong message display when mention is triggered
  src/ui/mucwin.c
Labels: bug

#1553 OMEMO: Separate handling of device list
  src/omemo/omemo.c
Labels: improvement

#1559 Add command to show single bookmark details
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/ui/console.c
  src/ui/ui.h
  src/xmpp/bookmark.c
  src/xmpp/xmpp.h
  tests/unittests/ui/stub_ui.c
  tests/unittests/xmpp/stub_xmpp.c
Labels: feature

#1560 XEP-0353: Display a notice when receiving a call
  src/xmpp/message.c
  src/xmpp/stanza.h
Labels: feature

#1561 Escape all parameters in SQL statements
  src/database.c
Labels: improvement

#1563 Fix log rotation
  src/log.c
Labels: bug

#1564 Disable notifications by default
  src/config/preferences.c
Labels: behaviour-change

#1565 OMEMO Logging
  src/omemo/omemo.c
  src/omemo/store.c
Labels: cleanup

#1567 Add support for XEP-0157 server contact information discovery
  src/command/cmd_defs.c
  src/ui/console.c
  src/ui/ui.h
  src/xmpp/iq.c
  src/xmpp/stanza.c
  src/xmpp/stanza.h
Labels: feature
