Repository profanity-im/profanity, pull requests merged in 2021-03, with the labels that each got.

#1495 MUC: Show offline members in sidebar
  src/command/cmd_ac.c
  src/command/cmd_funcs.c
  src/config/preferences.c
  src/config/preferences.h
  src/config/theme.c
  src/ui/console.c
  src/ui/mucwin.c
  src/ui/occupantswin.c
  src/ui/win_types.h
  src/ui/window.c
Labels: feature

#1498 Remove "file://" from file names
  src/common.c
Labels: improvement

#1500 Fix HTTP upload
  src/tools/http_upload.c
  src/tools/http_upload.h
  src/xmpp/iq.c
  src/xmpp/stanza.c
  src/xmpp/stanza.h
Labels: improvement

#1501 Add command to change password of logged in user
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/command/cmd_funcs.h
  src/ui/core.c
  src/ui/ui.h
  src/xmpp/connection.c
  src/xmpp/iq.c
  src/xmpp/stanza.c
  src/xmpp/stanza.h
  src/xmpp/xmpp.h
  tests/unittests/ui/stub_ui.c
  tests/unittests/xmpp/stub_xmpp.c
Labels: feature

#1502 Upload: Fix unused return
  src/tools/http_upload.c
Labels: improvement

#1503 Cleanup autocomplete
  src/tools/autocomplete.c
Labels: cleanup

#1504 MUC: Add voice request
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/xmpp/message.c
  src/xmpp/stanza.c
  src/xmpp/stanza.h
  src/xmpp/xmpp.h
  tests/unittests/xmpp/stub_xmpp.c
Labels: feature

#1508 Support to approve MUC voice requests
  src/xmpp/form.c
  src/xmpp/message.c
  src/xmpp/stanza.c
  src/xmpp/stanza.h
Labels: feature

#1511 Command doc: Improve description and examples of `/bookmark` and `/join`
  src/command/cmd_defs.c
Labels: improvement

#1510 Register nickname with MUC
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/xmpp/iq.c
  src/xmpp/stanza.c
  src/xmpp/stanza.h
  src/xmpp/xmpp.h
  tests/unittests/xmpp/stub_xmpp.c
Labels: feature

#1513 Fix potential problems caused by unexpected stanzas
  src/database.c
  src/event/server_events.c
  src/xmpp/avatar.c
  src/xmpp/iq.c
  src/xmpp/message.c
  src/xmpp/ox.c
  src/xmpp/stanza.c
Labels: cleanup, improvement
