Repository profanity-im/profanity, pull requests merged in 2021-12, with the labels that each got.

#1620 Re-Enable CI
  .github/workflows/main.yml
  Dockerfile.arch
  Dockerfile.ubuntu
Labels: tests, build

#1605 XEP 0107 - User Mood
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/command/cmd_funcs.h
  src/xmpp/iq.c
  src/xmpp/message.c
  src/xmpp/session.c
  src/xmpp/stanza.h
  src/xmpp/xmpp.h
  tests/unittests/xmpp/stub_xmpp.c
Labels: feature

#1622 use wildcard for man pages in Makefile.am
  Makefile.am
Labels: build

#1623 Upgrade to OpenBSD 7.0 in CI
  .builds/openbsd.yml
  ci-build.sh
Labels: build
