Repository profanity-im/profanity, pull requests merged in 2021-04, with the labels that each got.

#1515 [OMEMO] Fix sending messages
  src/command/cmd_funcs.c
  src/event/client_events.c
  src/omemo/omemo.c
  src/ui/chatwin.c
Labels: OMEMO, bug, improvement

#1506 OMEMO - trust mode
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/command/cmd_funcs.h
  src/config/preferences.c
  src/config/preferences.h
  src/omemo/omemo.c
Labels: feature

#1528 Apply pre_chat_message_display hook to history
  src/ui/chatwin.c
Labels: plugins
