Repository profanity-im/profanity, pull requests merged in 2021-11, with the labels that each got.

#1611 Fix OMEMO /sendfile on non-glibc systems
  src/command/cmd_funcs.c
Labels: bug, OMEMO

#1617 Make readline check more portable
  configure.ac
Labels: improvement, build

#1618 Fix carbons criteria
  src/xmpp/message.c
  src/xmpp/stanza.h
Labels: otr

#1616 gcc-12 fixes
  src/plugins/callbacks.c
  src/plugins/python_api.c
Labels: improvement

#1610 Fix message encryption for sender devices
  src/omemo/omemo.c
Labels: OMEMO
