Repository profanity-im/profanity, pull requests merged in 2022-05, with the labels that each got.

#1702 Fix autocomplete for `/ox discover`.
  src/command/cmd_ac.c
Labels: bug, ox

#1703 Several OX improvements
  docs/profanity-ox-setup.1
  docs/profanity-ox.md
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/pgp/gpg.c
  src/xmpp/message.c
  src/xmpp/ox.c
Labels: improvement, ox

#1705 Improvements for OX part 2
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/command/cmd_funcs.h
  src/config/preferences.c
  src/config/preferences.h
  src/ui/console.c
  src/ui/ui.h
  src/xmpp/message.c
  tests/unittests/ui/stub_ui.c
Labels: improvement, ox

#1707 Log encrypted messages by default to chatlog
  src/command/cmd_defs.c
  src/config/preferences.c
Labels: behaviour-change

#1708 DOAP: Use correct namespace for xmlns:schema
  profanity.doap
Labels: improvement

#1711 Fix room name not updating.
  src/xmpp/iq.c
Labels: improvement

#1715 Fix segfault on `/ox discover`
  src/xmpp/ox.c
Labels: improvement

#1716 Respect silent nick change in mucs
  src/xmpp/presence.c
Labels: improvement

#1712 Update capabilities of muc on available presence
  src/xmpp/iq.c
  src/xmpp/message.c
Labels: improvement

#1714 Add `/avatar set` command to publish avatar
  Dockerfile.arch
  Dockerfile.debian
  Dockerfile.fedora
  Dockerfile.tumbleweed
  Dockerfile.ubuntu
  ci-build.sh
  configure.ac
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/main.c
  src/xmpp/avatar.c
  src/xmpp/avatar.h
  src/xmpp/stanza.c
  src/xmpp/stanza.h
  tests/unittests/xmpp/stub_avatar.c
Labels: feature

#1568 Show OMEMO QR Code
  Dockerfile.arch
  Dockerfile.debian
  Dockerfile.fedora
  Dockerfile.tumbleweed
  Dockerfile.ubuntu
  ci-build.sh
  configure.ac
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/command/cmd_funcs.h
  src/ui/console.c
  src/ui/ui.h
  tests/unittests/ui/stub_ui.c
Labels: feature, help wanted
