Repository profanity-im/profanity, pull requests merged in 2022-02, with the labels that each got.

#1631 Fix #1628
  .clang-format
  src/command/cmd_funcs.c
  src/database.c
  src/event/server_events.c
  src/omemo/crypto.h
  src/omemo/omemo.c
  src/otr/otr.c
  src/pgp/gpg.c
  src/tools/clipboard.c
  src/ui/chatwin.c
  src/ui/console.c
  src/ui/notifier.c
  src/ui/occupantswin.c
  src/ui/window.c
  src/xmpp/avatar.c
  src/xmpp/connection.c
  src/xmpp/omemo.c
  src/xmpp/ox.c
  src/xmpp/ox.h
  src/xmpp/session.c
  src/xmpp/session.h
  src/xmpp/stanza.c
  src/xmpp/stanza.h
  src/xmpp/xmpp.h
  tests/unittests/test_callbacks.c
Labels: feature

#1635 fixed typo from "the Yes" to "to YES"
  apidocs/c/c-prof.conf
Labels: cleanup

#1640 Update the contributing guide
  CONTRIBUTING.md
Labels: organizational

#1641 Clean up configure.ac
  Makefile.am
  configure-plugins
  configure.ac
  src/omemo/store.c
  src/omemo/store.h
  src/otr/otrlibv3.c
Labels: cleanup, build

#1642 Fix python executed during configure
  configure.ac
  src/plugins/python_api.c
  src/plugins/python_plugins.c
Labels: bug, improvement, build
