Repository profanity-im/profanity, pull requests merged in 2022-09, with the labels that each got.

#1748 Fix for avatar opening executable
  src/common.c
  src/xmpp/avatar.c
Labels: improvement

#1749 Minor improvements
  src/log.c
  src/profanity.c
  src/tools/http_download.c
Labels: improvement, cleanup

#1752 typo in configure: enable_gdk_pixbuf not enable_pixbuf
  configure.ac
Labels: bug, cleanup

#1753 Fix typo in configure.ac
  configure.ac
Labels: bug, cleanup

#1755 Fix plugins managment
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
Labels: improvement, plugins

#1756 plugin: python: fix build for Python 3.11
  src/plugins/python_api.c
Labels: improvement, plugins
