Repository profanity-im/profanity, pull requests merged in 2022-03, with the labels that each got.

#1645 Add hotkey for sending readline text to editor
  Makefile.am
  src/command/cmd_funcs.c
  src/tools/editor.c
  src/tools/editor.h
  src/ui/inputwin.c
Labels: feature

#1648 Refactor editor & some other parts
  src/command/cmd_defs.c
  src/common.c
  src/common.h
  src/config/files.c
  src/config/files.h
  src/database.c
  src/log.c
  src/omemo/omemo.c
  src/otr/otr.c
  src/pgp/gpg.c
  src/tools/editor.c
  src/ui/inputwin.c
  src/xmpp/connection.c
  tests/unittests/helpers.c
Labels: improvement, cleanup

#1646 Fix not autocompleting nicks with '/'
  src/ui/inputwin.c
Labels: bug, improvement

#1644 Improve OX user experience
  src/command/cmd_ac.c
  src/command/cmd_funcs.c
  src/pgp/gpg.c
  src/xmpp/ox.c
Labels: improvement, ox

#1653 Fix crash on /editor
  src/tools/editor.c
Labels: bug

#1655 Reset url autocompletion after open/save
  src/command/cmd_funcs.c
Labels: improvement

#1658 Use EDITOR environment variable
  src/config/preferences.c
Labels: improvement

#1656 Add none option for /who
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/ui/mucwin.c
Labels: feature

#1659 Add debug information to binary
  configure.ac
Labels: improvement, build

#1660 Input window: handle invalid multibyte
  src/ui/inputwin.c
Labels: bug

#1665 More cleanup
  .github/workflows/main.yml
  .gitignore
  Makefile.am
  src/command/cmd_funcs.c
  src/config/preferences.c
  src/ui/window.c
  src/xmpp/connection.c
Labels: bug, improvement, tests, cleanup

#1666 Man page improvements
  docs/profanity.1
Labels: improvement
