Repository profanity-im/profanity, pull requests merged in 2022-10, with the labels that each got.

#1763 Gruvbox - Trung's Edition
  themes/gruvbox_transparent
Labels: theme

#1767 Fix first start detection
  src/ui/console.c
Labels: bug

#1760 Replace `call_external`'s implementation with an async one
  src/command/cmd_funcs.c
  src/common.c
  src/common.h
  src/tools/aesgcm_download.c
  src/tools/http_download.c
  src/xmpp/avatar.c
Labels: improvement

#1768 Improve /msg and /win autocompletion
  src/command/cmd_ac.c
Labels: improvement

#1724 MAM improvements
  src/database.c
  src/database.h
  src/event/server_events.c
  src/ui/buffer.c
  src/ui/buffer.h
  src/ui/chatwin.c
  src/ui/ui.h
  src/ui/window.c
  src/ui/window.h
  src/xmpp/iq.c
  src/xmpp/stanza.c
  src/xmpp/stanza.h
  src/xmpp/xmpp.h
Labels: feature

#1772 Fix segfault when loading from MAM
  src/ui/window.c
Labels: bug

#1773 Improve MAM loading string.
  src/ui/window.h
Labels: UI

#1774 Work around different clang-format versions
  src/config/color.c
Labels: tests
