Repository profanity-im/profanity, pull requests merged in 2022-06, with the labels that each got.

#1717 Fix duplicate messages in chat with oneself.
  src/ui/window.c
  src/xmpp/message.c
Labels: improvement

#1721 Improve cmd argument parser
  src/tools/parser.c
Labels: improvement

#1725 Make display of user mood optional
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/config/preferences.c
  src/config/preferences.h
  src/ui/console.c
  src/ui/ui.h
  src/xmpp/session.c
  tests/unittests/ui/stub_ui.c
Labels: feature

#1726 Switch log level while running
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/log.c
  src/log.h
  src/ui/console.c
Labels: feature

#1729 Various cleanups
  configure.ac
  src/chatlog.c
  src/config/accounts.c
  src/config/scripts.c
  src/database.c
  src/xmpp/stanza.c
Labels: cleanup

#1730 Don't scroll if not needed
  src/ui/window.c
Labels: improvement

#1731 Retrieve enc type from db
  src/database.c
Labels: improvement
