Repository profanity-im/profanity, pull requests merged in 2022-04, with the labels that each got.

#1671 Fix race condition on resize
  src/ui/core.c
Labels: bug, improvement

#1668 Document custom input configuration in man page
  docs/profanity.1
Labels: improvement

#1670 Even moar cleanup
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/ui/window.c
  tests/unittests/test_cmd_account.c
Labels: cleanup

#1669 Make all existing input functions bindable from config
  src/ui/inputwin.c
Labels: feature

#1667 Add Alt/Ctrl-arrows combinations for GNU Screen
  src/ui/inputwin.c
Labels: improvement

#1664 Tab completion code simplification
  src/ui/inputwin.c
Labels: cleanup

#1672 fix path where logs are stored
  src/log.c
Labels: bug

#1675 Use correct colour for their nick when showing history
  src/ui/window.c
Labels: improvement

#1681 fix theme load
  src/config/theme.c
Labels: bug

#1680 Add irssi theme
  profrc.example
  themes/irssi
Labels: theme

#1674 Allow bold for default colours
  src/config/theme.c
Labels: improvement

#1683 Include useful aliases in profrc example
  profrc.example
Labels: improvement

#1688 Mention C-x C-r (reload inputrc) in the man page
  docs/profanity.1
Labels: improvement

#1690 Show return symbol for embedded newlines
  src/command/cmd_funcs.c
  src/ui/inputwin.c
Labels: feature

#1699 Fix SIGABRT when using wrong argument order for receiving ox key
  src/command/cmd_funcs.c
  src/xmpp/ox.c
Labels: bug

#1697 Add support for offline MUC notifications
  profrc.example
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/config/preferences.c
  src/config/preferences.h
  src/event/server_events.c
  src/event/server_events.h
  src/ui/console.c
Labels: feature

#1663 Add stamp settings
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/command/cmd_funcs.h
  src/config/preferences.c
  src/config/preferences.h
  src/ui/window.c
  src/xmpp/roster_list.c
Labels: feature

#1700 Use ISO8601 as date format in log files
  src/log.c
Labels: improvement, behaviour-change

#1701 Log file improvements
  src/config/preferences.h
  src/log.c
Labels: behaviour-change, cleanup
