Repository profanity-im/profanity, pull requests merged in 2023-11, with the labels that each got.

#1908 Refactor tests to use the new cmocka test runner
  tests/functionaltests/functionaltests.c
  tests/functionaltests/proftest.c
  tests/functionaltests/proftest.h
  tests/unittests/helpers.c
  tests/unittests/helpers.h
  tests/unittests/test_muc.c
  tests/unittests/test_muc.h
  tests/unittests/unittests.c
Labels: tests

#1909 Add unicode support for correction char
  src/command/cmd_funcs.c
  src/config/preferences.c
  src/config/preferences.h
  src/config/theme.c
Labels: improvement, UI

#1910 Show encryption for historical messages
  src/ui/chatwin.c
  src/ui/mucwin.c
  src/ui/window.c
  src/ui/window.h
Labels: improvement, UI

#1914 Ensure instances of auto types are initialized
  .github/workflows/main.yml
  src/command/cmd_funcs.c
  src/database.c
  src/omemo/omemo.c
  src/ui/chatwin.c
  src/ui/console.c
  src/ui/mucwin.c
  src/ui/window.c
  src/ui/window.h
  src/xmpp/avatar.c
  src/xmpp/message.c
  src/xmpp/vcard.c
  src/xmpp/xmpp.h
Labels: improvement

#1902 Change DB structure
  src/database.c
  src/ui/chatwin.c
  src/ui/window.c
  src/xmpp/message.c
Labels: improvement

#1915 Handle potential NULL pointers in database
  src/database.c
Labels: improvement

#1919 Fix double free crash
  src/config/conflists.c
Labels: improvement

#1923 Format `test_cmd_otr.c`
  tests/unittests/test_cmd_otr.c
Labels: cleanup

#1920 Minor `config/conflists.c` refactoring
  src/config/conflists.c
Labels: cleanup

#1926 Do not check for unique `stanza-id` for MAM messages
  src/database.c
Labels: improvement

#1927 Handle alt+enter as newline char
  docs/profanity.1
  src/ui/inputwin.c
Labels: feature

#1930 Minor `inputwin.c` refactoring/cleanup
  src/ui/inputwin.c
Labels: cleanup

#1924 Fix unintended exits on some commands
  src/command/cmd_funcs.c
Labels: cleanup

#1931 Introduce `/redraw` command
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/command/cmd_funcs.h
Labels: feature

#1932 Fix mem leak in `conf_string_list_add`
  src/config/conflists.c
Labels: cleanup

#1918 Fix `prof_pre_chat_message_display` does not replace sent messages + minor refactoring
  src/plugins/plugins.c
  src/plugins/plugins.h
  src/ui/chatwin.c
Labels: improvement

#1912 Add new mode for statusbar tab behaviour
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/ui/statusbar.c
Labels: improvement

#1933 Improve string convertion error handling
  src/plugins/python_plugins.c
Labels: improvement
