Repository profanity-im/profanity, pull requests merged in 2023-05, with the labels that each got.

#1843 Add ability to disable avatar publishing
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/xmpp/avatar.c
  src/xmpp/avatar.h
  src/xmpp/stanza.c
  src/xmpp/stanza.h
  tests/unittests/xmpp/stub_avatar.c
Labels: feature

#1845 Improvements for /executable and /avatar code
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/config/preferences.c
Labels: improvement

#1847 Minor improvements
  src/command/cmd_funcs.c
  src/event/client_events.c
  src/event/client_events.h
  src/event/server_events.c
  src/xmpp/connection.c
  src/xmpp/connection.h
  src/xmpp/iq.c
  src/xmpp/session.h
  src/xmpp/xmpp.h
  tests/unittests/xmpp/stub_xmpp.c
Labels: improvement, cleanup

#1839 Cleanup: gchar as gchar instead of char
  src/chatlog.c
  src/command/cmd_ac.c
  src/common.c
  src/config/files.c
  src/config/preferences.c
  src/config/theme.c
  src/config/tlscerts.c
  src/event/server_events.c
  src/main.c
  src/omemo/omemo.c
  src/omemo/store.c
  src/plugins/python_plugins.c
  src/profanity.c
  src/tools/autocomplete.c
  src/tools/http_upload.c
  src/ui/confwin.c
  src/ui/mucwin.c
  src/xmpp/capabilities.c
  src/xmpp/jid.c
  src/xmpp/message.c
  src/xmpp/omemo.c
  src/xmpp/stanza.c
  tests/unittests/test_cmd_join.c
  tests/unittests/test_cmd_otr.c
  tests/unittests/test_common.c
Labels: cleanup

#1848 Minor improvements
  configure.ac
  src/common.h
  src/database.c
  src/database.h
  src/tools/editor.c
  src/ui/chatwin.c
  src/ui/inputwin.c
  src/ui/ui.h
  src/xmpp/iq.c
  src/xmpp/stanza.c
Labels: cleanup

#1853 Fix 1852
  src/xmpp/iq.c
Labels: improvement
