Repository profanity-im/profanity, pull requests merged in 2023-12, with the labels that each got.

#1824 Smooth scrolling support (+mouse wheel scrolling in some terminals)
  docs/profanity.1
  src/command/cmd_funcs.c
  src/ui/inputwin.c
  src/ui/window.c
  src/ui/window.h
Labels: feature

#1937 Fix scrolling state at windows edge
  src/ui/win_types.h
  src/ui/window.c
Labels: improvement

#1944 Fix when feature discovery is finished
  src/event/server_events.c
  src/xmpp/iq.c
  src/xmpp/iq.h
  tests/unittests/xmpp/stub_xmpp.c
Labels: bug
