Repository profanity-im/profanity, pull requests merged in 2023-04, with the labels that each got.

#1807 Fix typos and add codespell configuration
  .codespellrc
  src/log.c
  src/xmpp/vcard.c
  tests/unittests/test_parser.c
Labels: improvement

#1809 Add autocomplete for the /reconnect command
  src/command/cmd_ac.c
Labels: improvement

#1811 themes/batman: Use "bold_black" iso "black_bold"
  themes/batman
Labels: improvement, theme

#1814 Improvements and bugfixes
  src/command/cmd_ac.c
  src/tools/autocomplete.c
  src/ui/confwin.c
Labels: improvement

#1813 add `/statusbar tabmode actlist`
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/config/preferences.c
  src/config/preferences.h
  src/ui/console.c
  src/ui/statusbar.c
Labels: feature

#1815 Feature: Allow setting client identification name/version manually
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/config/account.c
  src/config/account.h
  src/config/accounts.c
  src/config/accounts.h
  src/ui/console.c
  src/xmpp/iq.c
  src/xmpp/stanza.c
  tests/unittests/config/stub_accounts.c
  tests/unittests/test_cmd_account.c
  tests/unittests/test_cmd_connect.c
  tests/unittests/test_cmd_join.c
  tests/unittests/test_cmd_otr.c
  tests/unittests/test_cmd_rooms.c
Labels: feature

#1817 JID Display in Titlebar and Fix
  src/command/cmd_defs.c
  src/ui/statusbar.c
  src/ui/window.c
Labels: improvement

#1822 Hotfix stanza release
  src/xmpp/iq.c
Labels: improvement

#1826 Add nickname support for `/roster remove`
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  tests/functionaltests/functionaltests.c
  tests/functionaltests/test_roster.c
  tests/functionaltests/test_roster.h
  tests/unittests/test_cmd_roster.c
  tests/unittests/test_cmd_roster.h
  tests/unittests/unittests.c
Labels: feature

#1828 Use GH action for code style check
  .git-blame-ignore-revs
  .github/workflows/main.yml
  src/config/color.c
  src/plugins/c_api.c
  src/plugins/profapi.c
  src/plugins/profapi.h
Labels: tests

#1830 Add spellcheck to CI
  .github/workflows/main.yml
Labels: tests

#1831 Add encryption section to man page
  docs/profanity.1
Labels: otr, OMEMO, ox, pgp, docu

#1829 Don't add the same command twice to history
  src/ui/inputwin.c
Labels: improvement

#1827 New Feature: Session Alarm
  .gitignore
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/config/account.c
  src/config/account.h
  src/config/accounts.c
  src/config/accounts.h
  src/ui/console.c
  src/xmpp/connection.c
  src/xmpp/presence.c
  src/xmpp/xmpp.h
  tests/unittests/config/stub_accounts.c
  tests/unittests/test_cmd_account.c
  tests/unittests/test_cmd_connect.c
  tests/unittests/test_cmd_join.c
  tests/unittests/test_cmd_otr.c
  tests/unittests/test_cmd_rooms.c
Labels: feature

#1835 Fix crash, add consistency to logging
  src/command/cmd_funcs.c
  src/event/server_events.c
Labels: improvement

#1837 Fix two recently introduced memleaks
  src/ui/inputwin.c
  src/xmpp/stanza.c
Labels: bug

#1840 Fix `/plugins update`
  src/command/cmd_funcs.c
Labels: improvement
