Repository profanity-im/profanity, pull requests merged in 2023-10, with the labels that each got.

#1891 Minor improvements
  .github/pull_request_template.md
  .gitignore
  src/config/accounts.c
  src/event/server_events.c
  src/xmpp/iq.c
  src/xmpp/message.c
  src/xmpp/presence.c
  src/xmpp/roster_list.c
  src/xmpp/xmpp.h
Labels: improvement

#1892 Improve MUC title behaviour for roster, statusbar, and titlebar
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/config/preferences.c
  src/config/preferences.h
  src/config/theme.c
  src/ui/console.c
  src/ui/mucwin.c
  src/ui/rosterwin.c
  src/ui/statusbar.c
  src/ui/ui.h
  src/ui/window.c
  src/xmpp/iq.c
  src/xmpp/message.c
  themes/boothj5
  themes/boothj5_slack
  themes/jubalian
Labels: improvement

#1896 Fix 2 crashes on reconnection
  src/command/cmd_funcs.c
  src/event/client_events.c
  src/ui/window.c
Labels: improvement

#1898 Check sender for LMC messages
  src/database.c
Labels: improvement

#1900 Add params support for aliases
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
Labels: feature

#1905 Improve history paging performance
  src/ui/buffer.c
  src/ui/window.c
Labels: improvement

#1904 Add section `Using profanity` to profanity.1
  docs/profanity.1
Labels: docu

#1906 Fix loading of encryption type
  src/database.c
Labels: improvement
