Repository profanity-im/profanity, pull requests merged in 2023-07, with the labels that each got.

#1850 Extend `/pgp` command to make key exchange procedure easier
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/config/preferences.c
  src/config/preferences.h
  src/pgp/gpg.c
  src/pgp/gpg.h
  src/ui/chatwin.c
  tests/unittests/pgp/stub_gpg.c
  tests/unittests/test_cmd_pgp.c
Labels: feature, pgp

#1857 DB History Switcher, cleanup, mem leak fix
  src/chatlog.c
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/command/cmd_funcs.h
  src/config/preferences.c
  src/config/preferences.h
  src/config/theme.c
  src/database.c
  src/event/server_events.c
  src/omemo/omemo.c
  src/otr/otr.c
  src/tools/http_download.c
  src/tools/http_upload.c
  src/ui/chatwin.c
  src/ui/console.c
  src/ui/core.c
  src/ui/rosterwin.c
  src/ui/statusbar.c
  src/ui/window.c
  src/xmpp/roster_list.c
  src/xmpp/roster_list.h
  src/xmpp/session.c
  tests/unittests/test_cmd_otr.c
  tests/unittests/test_cmd_presence.c
  tests/unittests/test_preferences.c
Labels: feature, cleanup

#1865 Fix OMEMO autodetection in autotools
  configure.ac
Labels: OMEMO, build

#1858 Major cleanup
  src/chatlog.c
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/common.c
  src/common.h
  src/config/account.c
  src/config/accounts.c
  src/config/accounts.h
  src/config/cafile.c
  src/config/conflists.c
  src/config/files.c
  src/config/preferences.c
  src/config/preferences.h
  src/config/theme.c
  src/config/tlscerts.c
  src/database.c
  src/event/server_events.c
  src/log.c
  src/omemo/omemo.c
  src/otr/otr.c
  src/pgp/gpg.c
  src/plugins/c_api.c
  src/plugins/callbacks.c
  src/plugins/plugins.c
  src/plugins/themes.c
  src/tools/parser.c
  src/ui/console.c
  src/ui/core.c
  src/ui/inputwin.c
  src/ui/notifier.c
  src/ui/occupantswin.c
  src/ui/privwin.c
  src/ui/rosterwin.c
  src/ui/statusbar.c
  src/ui/tray.c
  src/ui/window.c
  src/ui/window_list.c
  src/xmpp/avatar.c
  src/xmpp/bookmark.c
  src/xmpp/capabilities.c
  src/xmpp/chat_session.c
  src/xmpp/connection.c
  src/xmpp/iq.c
  src/xmpp/jid.c
  src/xmpp/jid.h
  src/xmpp/message.c
  src/xmpp/muc.c
  src/xmpp/omemo.c
  src/xmpp/presence.c
  src/xmpp/roster.c
  src/xmpp/roster_list.c
  src/xmpp/session.c
  src/xmpp/stanza.c
  src/xmpp/stanza.h
  src/xmpp/vcard.c
  tests/unittests/config/stub_accounts.c
Labels: cleanup

#1869 Fix crash if we don't get `first` stanza during RSM
  profanity.doap
  src/xmpp/iq.c
Labels: bug

#1870 Move related commands as subcommands into /privacy
  src/command/cmd_ac.c
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/common.c
  src/common.h
  src/main.c
  src/profanity.c
  src/ui/console.c
  src/ui/core.c
  src/ui/ui.h
  src/xmpp/capabilities.c
  src/xmpp/iq.c
  src/xmpp/stanza.c
  tests/unittests/ui/stub_ui.c
Labels: feature
