Repository profanity-im/profanity, pull requests merged in 2023-01, with the labels that each got.

#1784 Make `/url save` autocomplete filenames after a url
  src/command/cmd_ac.c
Labels: improvement

#1787 Fix xscreensaver detection
  configure.ac
Labels: bug

#1780 Minor improvements
  .gitignore
  src/command/cmd_ac.c
  src/command/cmd_ac.h
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/command/cmd_funcs.h
  src/common.c
  src/common.h
  src/config/account.c
  src/config/account.h
  src/config/accounts.c
  src/config/preferences.c
  src/config/preferences.h
  src/database.c
  src/log.c
  src/log.h
  src/omemo/omemo.c
  src/omemo/store.c
  src/omemo/store.h
  src/profanity.c
  src/tools/autocomplete.c
  src/tools/editor.c
  src/ui/console.c
  src/ui/ui.h
  src/ui/window.c
  src/xmpp/chat_session.c
  src/xmpp/chat_session.h
  src/xmpp/connection.c
  src/xmpp/iq.c
  src/xmpp/jid.c
  src/xmpp/jid.h
  src/xmpp/message.c
  src/xmpp/session.c
  src/xmpp/session.h
  tests/unittests/log/stub_log.c
  tests/unittests/test_cmd_account.c
  tests/unittests/test_cmd_connect.c
  tests/unittests/test_cmd_join.c
  tests/unittests/test_cmd_otr.c
  tests/unittests/test_cmd_rooms.c
  tests/unittests/ui/stub_ui.c
  tests/unittests/xmpp/stub_xmpp.c
Labels: feature

#1786 Don't pass NULL pointers to vprintf
  src/common.h
  src/omemo/omemo.c
  src/xmpp/message.c
  src/xmpp/omemo.c
Labels: improvement

#1788 Minor improvements
  src/xmpp/connection.c
  src/xmpp/iq.c
Labels: improvement
