Repository profanity-im/profanity, pull requests merged in 2024-06, with the labels that each got.

#1972 Remove subscription when reporting spam/abuse
  src/command/cmd_funcs.c
Labels: feature

#1973 Check whether we are already in an omemo session for MUCs as well
  src/command/cmd_funcs.c
Labels: improvement

#1981 Minor improvements
  src/command/cmd_funcs.c
  src/event/client_events.c
  src/event/server_events.c
  src/omemo/omemo.c
  src/otr/otr.c
  src/plugins/plugins.c
  src/ui/chatwin.c
  src/ui/console.c
  src/xmpp/bookmark.c
  src/xmpp/jid.c
  src/xmpp/message.c
  src/xmpp/presence.c
  src/xmpp/session.c
  src/xmpp/xmpp.h
  tests/unittests/xmpp/stub_xmpp.c
Labels: improvement

#1979 Fix memleaks
  src/command/cmd_funcs.c
  src/ui/buffer.c
  src/xmpp/omemo.c
Labels: improvement

#1982 Reset autoconnect account when the account gets removed
  src/command/cmd_funcs.c
Labels: improvement

#1978 Make statusbar actlist respect the /statusbar show setting
  src/ui/statusbar.c
Labels: feature

#1983 Change default download location
  src/command/cmd_defs.c
  src/command/cmd_funcs.c
  src/config/files.c
  src/config/files.h
Labels: behaviour-change
